/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef python_cpp_CONSTANTS_H
#define python_cpp_CONSTANTS_H

#include "python_cpp_types.h"



class python_cppConstants {
 public:
  python_cppConstants();

};

extern const python_cppConstants g_python_cpp_constants;



#endif
