/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "python_cpp_constants.h"



const python_cppConstants g_python_cpp_constants;

python_cppConstants::python_cppConstants() {
}



