/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef getFeatures_H
#define getFeatures_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "pythonCpp_types.h"



#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class getFeaturesIf {
 public:
  virtual ~getFeaturesIf() {}
  virtual void returnFeature(std::vector<double> & _return, const std::vector<double> & input) = 0;
  virtual void matchFeatures(std::vector<int32_t> & _return, const std::vector<double> & feature_1, const std::vector<double> & feature_2) = 0;
};

class getFeaturesIfFactory {
 public:
  typedef getFeaturesIf Handler;

  virtual ~getFeaturesIfFactory() {}

  virtual getFeaturesIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(getFeaturesIf* /* handler */) = 0;
};

class getFeaturesIfSingletonFactory : virtual public getFeaturesIfFactory {
 public:
  getFeaturesIfSingletonFactory(const ::apache::thrift::stdcxx::shared_ptr<getFeaturesIf>& iface) : iface_(iface) {}
  virtual ~getFeaturesIfSingletonFactory() {}

  virtual getFeaturesIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(getFeaturesIf* /* handler */) {}

 protected:
  ::apache::thrift::stdcxx::shared_ptr<getFeaturesIf> iface_;
};

class getFeaturesNull : virtual public getFeaturesIf {
 public:
  virtual ~getFeaturesNull() {}
  void returnFeature(std::vector<double> & /* _return */, const std::vector<double> & /* input */) {
    return;
  }
  void matchFeatures(std::vector<int32_t> & /* _return */, const std::vector<double> & /* feature_1 */, const std::vector<double> & /* feature_2 */) {
    return;
  }
};

typedef struct _getFeatures_returnFeature_args__isset {
  _getFeatures_returnFeature_args__isset() : input(false) {}
  bool input :1;
} _getFeatures_returnFeature_args__isset;

class getFeatures_returnFeature_args {
 public:

  getFeatures_returnFeature_args(const getFeatures_returnFeature_args&);
  getFeatures_returnFeature_args& operator=(const getFeatures_returnFeature_args&);
  getFeatures_returnFeature_args() {
  }

  virtual ~getFeatures_returnFeature_args() throw();
  std::vector<double>  input;

  _getFeatures_returnFeature_args__isset __isset;

  void __set_input(const std::vector<double> & val);

  bool operator == (const getFeatures_returnFeature_args & rhs) const
  {
    if (!(input == rhs.input))
      return false;
    return true;
  }
  bool operator != (const getFeatures_returnFeature_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const getFeatures_returnFeature_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class getFeatures_returnFeature_pargs {
 public:


  virtual ~getFeatures_returnFeature_pargs() throw();
  const std::vector<double> * input;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _getFeatures_returnFeature_result__isset {
  _getFeatures_returnFeature_result__isset() : success(false) {}
  bool success :1;
} _getFeatures_returnFeature_result__isset;

class getFeatures_returnFeature_result {
 public:

  getFeatures_returnFeature_result(const getFeatures_returnFeature_result&);
  getFeatures_returnFeature_result& operator=(const getFeatures_returnFeature_result&);
  getFeatures_returnFeature_result() {
  }

  virtual ~getFeatures_returnFeature_result() throw();
  std::vector<double>  success;

  _getFeatures_returnFeature_result__isset __isset;

  void __set_success(const std::vector<double> & val);

  bool operator == (const getFeatures_returnFeature_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const getFeatures_returnFeature_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const getFeatures_returnFeature_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _getFeatures_returnFeature_presult__isset {
  _getFeatures_returnFeature_presult__isset() : success(false) {}
  bool success :1;
} _getFeatures_returnFeature_presult__isset;

class getFeatures_returnFeature_presult {
 public:


  virtual ~getFeatures_returnFeature_presult() throw();
  std::vector<double> * success;

  _getFeatures_returnFeature_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _getFeatures_matchFeatures_args__isset {
  _getFeatures_matchFeatures_args__isset() : feature_1(false), feature_2(false) {}
  bool feature_1 :1;
  bool feature_2 :1;
} _getFeatures_matchFeatures_args__isset;

class getFeatures_matchFeatures_args {
 public:

  getFeatures_matchFeatures_args(const getFeatures_matchFeatures_args&);
  getFeatures_matchFeatures_args& operator=(const getFeatures_matchFeatures_args&);
  getFeatures_matchFeatures_args() {
  }

  virtual ~getFeatures_matchFeatures_args() throw();
  std::vector<double>  feature_1;
  std::vector<double>  feature_2;

  _getFeatures_matchFeatures_args__isset __isset;

  void __set_feature_1(const std::vector<double> & val);

  void __set_feature_2(const std::vector<double> & val);

  bool operator == (const getFeatures_matchFeatures_args & rhs) const
  {
    if (!(feature_1 == rhs.feature_1))
      return false;
    if (!(feature_2 == rhs.feature_2))
      return false;
    return true;
  }
  bool operator != (const getFeatures_matchFeatures_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const getFeatures_matchFeatures_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class getFeatures_matchFeatures_pargs {
 public:


  virtual ~getFeatures_matchFeatures_pargs() throw();
  const std::vector<double> * feature_1;
  const std::vector<double> * feature_2;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _getFeatures_matchFeatures_result__isset {
  _getFeatures_matchFeatures_result__isset() : success(false) {}
  bool success :1;
} _getFeatures_matchFeatures_result__isset;

class getFeatures_matchFeatures_result {
 public:

  getFeatures_matchFeatures_result(const getFeatures_matchFeatures_result&);
  getFeatures_matchFeatures_result& operator=(const getFeatures_matchFeatures_result&);
  getFeatures_matchFeatures_result() {
  }

  virtual ~getFeatures_matchFeatures_result() throw();
  std::vector<int32_t>  success;

  _getFeatures_matchFeatures_result__isset __isset;

  void __set_success(const std::vector<int32_t> & val);

  bool operator == (const getFeatures_matchFeatures_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const getFeatures_matchFeatures_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const getFeatures_matchFeatures_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _getFeatures_matchFeatures_presult__isset {
  _getFeatures_matchFeatures_presult__isset() : success(false) {}
  bool success :1;
} _getFeatures_matchFeatures_presult__isset;

class getFeatures_matchFeatures_presult {
 public:


  virtual ~getFeatures_matchFeatures_presult() throw();
  std::vector<int32_t> * success;

  _getFeatures_matchFeatures_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class getFeaturesClient : virtual public getFeaturesIf {
 public:
  getFeaturesClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  getFeaturesClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void returnFeature(std::vector<double> & _return, const std::vector<double> & input);
  void send_returnFeature(const std::vector<double> & input);
  void recv_returnFeature(std::vector<double> & _return);
  void matchFeatures(std::vector<int32_t> & _return, const std::vector<double> & feature_1, const std::vector<double> & feature_2);
  void send_matchFeatures(const std::vector<double> & feature_1, const std::vector<double> & feature_2);
  void recv_matchFeatures(std::vector<int32_t> & _return);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class getFeaturesProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::apache::thrift::stdcxx::shared_ptr<getFeaturesIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (getFeaturesProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_returnFeature(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_matchFeatures(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  getFeaturesProcessor(::apache::thrift::stdcxx::shared_ptr<getFeaturesIf> iface) :
    iface_(iface) {
    processMap_["returnFeature"] = &getFeaturesProcessor::process_returnFeature;
    processMap_["matchFeatures"] = &getFeaturesProcessor::process_matchFeatures;
  }

  virtual ~getFeaturesProcessor() {}
};

class getFeaturesProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  getFeaturesProcessorFactory(const ::apache::thrift::stdcxx::shared_ptr< getFeaturesIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::apache::thrift::stdcxx::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::apache::thrift::stdcxx::shared_ptr< getFeaturesIfFactory > handlerFactory_;
};

class getFeaturesMultiface : virtual public getFeaturesIf {
 public:
  getFeaturesMultiface(std::vector<apache::thrift::stdcxx::shared_ptr<getFeaturesIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~getFeaturesMultiface() {}
 protected:
  std::vector<apache::thrift::stdcxx::shared_ptr<getFeaturesIf> > ifaces_;
  getFeaturesMultiface() {}
  void add(::apache::thrift::stdcxx::shared_ptr<getFeaturesIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void returnFeature(std::vector<double> & _return, const std::vector<double> & input) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->returnFeature(_return, input);
    }
    ifaces_[i]->returnFeature(_return, input);
    return;
  }

  void matchFeatures(std::vector<int32_t> & _return, const std::vector<double> & feature_1, const std::vector<double> & feature_2) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->matchFeatures(_return, feature_1, feature_2);
    }
    ifaces_[i]->matchFeatures(_return, feature_1, feature_2);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class getFeaturesConcurrentClient : virtual public getFeaturesIf {
 public:
  getFeaturesConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  getFeaturesConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void returnFeature(std::vector<double> & _return, const std::vector<double> & input);
  int32_t send_returnFeature(const std::vector<double> & input);
  void recv_returnFeature(std::vector<double> & _return, const int32_t seqid);
  void matchFeatures(std::vector<int32_t> & _return, const std::vector<double> & feature_1, const std::vector<double> & feature_2);
  int32_t send_matchFeatures(const std::vector<double> & feature_1, const std::vector<double> & feature_2);
  void recv_matchFeatures(std::vector<int32_t> & _return, const int32_t seqid);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif



#endif
