/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef pythonCpp_CONSTANTS_H
#define pythonCpp_CONSTANTS_H

#include "pythonCpp_types.h"



class pythonCppConstants {
 public:
  pythonCppConstants();

};

extern const pythonCppConstants g_pythonCpp_constants;



#endif
