/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "pythonCpp_constants.h"



const pythonCppConstants g_pythonCpp_constants;

pythonCppConstants::pythonCppConstants() {
}



